name: app_lockout
description: "AppLockout Flutter UI with native Android restriction engine."
publish_to: 'none'
version: 0.6.0-alpha.1+19

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
